spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bside?useSSL=false
    username: root
    password: dhtlgns731!

  OAuth2:
    google:
      url: https://accounts.google.com/o/oauth2/v2/auth
      token-request-url: https://oauth2.googleapis.com/token
      user-info-request-url: https://www.googleapis.com/oauth2/v1/userinfo
      client-id: http://83894557482-v5cbgg6jot99hrs1rl80cj55gc75dhfc.apps.googleusercontent.com
      client-secret: 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
      callback-url: http://localhost:8080/login/auth/google-callback
      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile

    kakao:
      url: https://kauth.kakao.com/oauth/authorize
      token-request-url: https://kauth.kakao.com/oauth/token
      client-id: 5a93db408aa5e800df2c9f3ceaefd5e2
      redirect-url: http://localhost:8080/login/auth/kakao-callback
      user-info-uri: https://kapi.kakao.com/v2/user/me

    apple:
      url: https://appleid.apple.com
      team-id: XQ24HP64B3
      redirect-url: https://nottodo.store:8080/login/auth/apple-callback
      client-id: nottodo.bside.com #com.bside.nottodo
      key-id: T4JHR24JQW
      key-path: AuthKey_T4JHR24JQW.p8 #key.p8

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 823576274300-8qa3bceguhvjo8201lk0g03bt0j3j036.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          kakao:
            client-id: cadf09063078f68abe9b618450a72d18
            client-secret: Jcui3KnJ2joNJHsqayINbvDfoNCeNIxC
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: POST

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?&response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://appleid.apple.com/auth/userinfo
server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: dhtlgns731!
    key-store-type: PKCS12
    key-alias: bns-ssl
app:
  auth:
    tokenExpiry: 10000
    tokenSecret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
    accessTokenSecret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLXN1bmdhLXNwcmluZy1ib290LXNlY3VyaXR5LWp3dC10dXRvcmlhbC1hY2Nlc3MK
    refreshTokenSecret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLXN1bmdhLXNwcmluZy1ib290LXNlY3VyaXR5LWp3dC10dXRvcmlhbC1yZWZyZXNoCg==