spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bside
    username: root
    password: bsideTeam6!

  OAuth2:
    google:
      url: https://accounts.google.com/o/oauth2/v2/auth
      token-request-url: https://oauth2.googleapis.com/token
      user-info-request-url: https://www.googleapis.com/oauth2/v1/userinfo
      client-id:
      client-secret:
      callback-url: http://localhost:8080/login/auth/google-callback
      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile

    kakao:
      url: https://kauth.kakao.com/oauth/authorize
      token-request-url: https://kauth.kakao.com/oauth/token
      client-id: 5a93db408aa5e800df2c9f3ceaefd5e2
      redirect-url: http://localhost:8080/login/auth/kakao-callback
      user-info-uri: https://kapi.kakao.com/v2/user/me

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile
          kakao:
            client-id:
            client-secret:
            scope:
              - account_email
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
            client-authentication-method: POST
          naver:
            client-id:
            client-secret:
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          apple:
            client-id:
            client-secret:
            redirect-uri: https://github.com
            scope:
              - name
              - email
            clkent-name: Apple
            authorization-grant-type: authorization_code
            response-mode: form_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?&response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://appleid.apple.com/auth/userinfo